ccflags-y += -I$(srctree)/kernel/msm-5.4/include/soc/oplus/

oplus_chg_v2-y += oplus_chg_core.o
oplus_chg_v2-y += oplus_debug_info.o
oplus_chg_v2-y += oplus_charger.o
oplus_chg_v2-y += oplus_vooc.o
oplus_chg_v2-y += oplus_adapter.o
oplus_chg_v2-y += oplus_short.o
oplus_chg_v2-y += oplus_wireless.o
oplus_chg_v2-y += oplus_configfs.o
oplus_chg_v2-y += oplus_chg_ops_manager.o
oplus_chg_v2-y += oplus_chg_gki.o
oplus_chg_v2-y += oplus_chg_voter.o
oplus_chg_v2-y += oplus_chg_wired.o
oplus_chg_v2-y += oplus_chg_comm.o
oplus_chg_v2-y += oplus_chg_vooc.o

oplus_chg_v2-y += adapter_ic/oplus_stm.o

oplus_chg_v2-y += charger_ic/oplus_short_ic.o
oplus_chg_v2-y += charger_ic/oplus_virtual_charger.o

oplus_chg_v2-y += gauge_ic/oplus_hal_bq27541.o

oplus_chg_v2-y += vooc_ic/oplus_hal_rk826.o
oplus_chg_v2-y += vooc_ic/oplus_hal_vooc.o

oplus_chg_v2-y += wireless_ic/oplus_p922x.o
oplus_chg_v2-y += wireless_ic/oplus_nu1619.o
oplus_chg_v2-y += wireless_ic/oplus_chargepump.o

oplus_chg_v2-y += hal/oplus_chg_ic.o
oplus_chg_v2-y += hal/oplus_virtual_buck.o
oplus_chg_v2-y += hal/oplus_virtual_asic.o
oplus_chg_v2-y += hal/oplus_virtual_gauge.o
oplus_chg_v2-y += hal/oplus_hal_vooc.o

oplus_chg_v2-y += mms/oplus_mms.o
oplus_chg_v2-y += mms/oplus_mms_gauge.o
oplus_chg_v2-y += mms/oplus_mms_wired.o

oplus_chg_v2-y += strategy/oplus_strategy.o
oplus_chg_v2-y += strategy/oplus_strategy_cgcl.o

oplus_chg_v2-$(CONFIG_OPLUS_SM8350_CHARGER) += charger_ic/oplus_hal_sm8350.o charger_ic/oplus_da9313.o charger_ic/oplus_hal_mp2650.o

ccflags-y += -DCONFIG_OPLUS_CHG_IC_DEBUG -DCONFIG_OPLUS_CHG_MMS_DEBUG
KBUILD_LDS_MODULE_ATTACH = $(srctree)/drivers/power/oplus_v2/oplus_chg_module.lds

obj-$(CONFIG_OPLUS_CHG) := oplus_chg_v2.o

