#
# Makefile for the wifi cap center.
# XuFenghua@CONNECTIVITY.WIFI.BASIC.CAPCENTER.190453, OPLUS_FEATURE_WIFI_CAPCENTER
#
KBUILD_CFLAGS += -Wno-unused-variable -Wno-unused-function
obj-$(CONFIG_OPLUS_FEATURE_WIFI_CAPCENTER) += oplus_wificapcenter.o
